---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  labels:
    app: nextjs
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: nextjs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nextjs-env
      terminationGracePeriodSeconds: 180